name: Feature Request
description: Suggest an idea for KodaDot to be better for your friends
title: "Be descriptive and short"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature-request
    attributes:
      label: Is your feature request related to a problem? 
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when [...]
      value: "I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like
      description:  A clear and concise description of what you want to happen.
      placeholder: I would like to see
      value: "I would like to see"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
      placeholder: I have tried this alternative
      value: "I have tried this alternative"
    validations:
      required: true
