export type NeoButtonVariant =
  | 'primary'
  | 'info'
  | 'success'
  | 'warning'
  | 'danger'
  | 'k-accent'
  | 'k-blue'
  | 'connect'
  | 'connect-dropdown'
  | 'icon'
  | 'unlockable'
  | 'disabled-secondary'

export type NftCardVariant = 'primary' | 'minimal'
