name: Cypress Tests

on:
  workflow_dispatch:
    push:
      branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        job: [ 0, 1, 2, 3]
    container:
      image: cypress/included:10.6.0
      options: --user 1001
    env:
      CYPRESS_CACHE_FOLDER: '${GITHUB_WORKSPACE}/.cypress-cache'
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          run: pnpm generate

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: ~/.pnpm-store
  ui-chrome-tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: cypress/included:10.6.0
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]

    steps:
      - uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: "E2E tests - chrome"
        uses: cypress-io/github-action@v4
        with:
          project: ./tests
          start: pnpm start:static
          wait-on: 'http://localhost:9090'
          wait-on-timeout: 150
          parallel: true
          command: pnpm test:e2e --browser chrome
