name: Cypress Tests

on:
  workflow_dispatch:
    push:
      branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:10.6.0
      options: --user 1001
    env:
      CYPRESS_CACHE_FOLDER: '${GITHUB_WORKSPACE}/.cypress-cache'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          run: pnpm generate

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: ~/.pnpm-store

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:10.6.0
      options: --user 1001
    env:
      CYPRESS_CACHE_FOLDER: '${GITHUB_WORKSPACE}/.cypress-cache'
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: cache-and-install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [ 1, 2, 3, 4, 5 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ~/.pnpm-store

      - name: E2E test
        uses: cypress-io/github-action@v4
        with:
          project: ./tests/e2e/*
          build: pnpm generate
          start: pnpm start:static
          wait-on: http://localhost:9090
          wait-on-timeout: 150
          command: run --browser chrome --headless --spec "cypress/integration/ui/**/*"
#  ui-chrome-tests:
#    timeout-minutes: 20
#    runs-on: ubuntu-latest
#    container:
#      image: cypress/included:10.6.0
#      options: --user 1001
#    needs: install
#    strategy:
#      fail-fast: false
#      matrix:
#        containers: [1, 2, 3, 4]
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Download the build folders
#        uses: actions/download-artifact@v3
#        with:
#          name: build
#          path: build
#
#      - name: "E2E tests - chrome"
#        uses: cypress-io/github-action@v4
#        with:
#          project: ./tests
#          build: pnpm generate
#          start: pnpm start:static
#          wait-on: 'http://localhost:9090'
#          wait-on-timeout: 150
#          parallel: true
#          command: pnpm test:e2e --browser chrome
