name: pr-chatter

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: BrianMitchL/pr-chatter-action@v1
        with:
          TENOR_API_KEY: T0FSGDPQMCIT
          approved-gif-keywords: 'amazing, approve, awesome, great work, good job, hooray, incredible, joy, looks good, nice, perfect, thumbs up, wonderful'
          changes-requested-gif-keywords: 'try again, review, at least you tried, so close, dumpster fire, terrible, awful, disgusting, sad'
