# # This is a basic workflow to help you get started with Actions

# name: sentiment-pr

# # Controls when the action will run.
# on:
#   pull_request:
#     types: [opened]
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: TerabyteTiger/action-happyPR@v3
#         id: happy
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
